name: Create a pull request on master branch.

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      title:
        required: true
      version:   
        description: 'Enter release version label'
        required: true
        type: choice
        options: 
          - patch
          - minor
          - major

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release"                                
          destination_branch: "master"                               
          pr_title: ${{ github.event.inputs.title }}               
          pr_label: ${{ github.event.inputs.version }}                             
          github_token: ${{ secrets.GITHUB_TOKEN }}
